### ISSUE TITLE
Hi, could you help me with a GET function?

### ISSUE THREAD

**Issue by matallana** [hisk/james-auth#2]
hello, im using the james auth in a self project based on roles and authentification, the wiki and inner comments are fine but the get method that are already used is short, i mean, the function give me a name, or whatever information from the main user table, but if i want to show others tables or multiple tables, how could i do it in this case?
You really help me so much if i could read a basic get function, to give me data from mysql

sorry for my english, isn't native.

Greetings.

**Comment by jilvin** [comment]
@matallana You can read the Sequelize JS documentation. It's pretty easy. Also, you can create more routes as per your requirement. 👍
